#!/bin/bash

################-> are comments
################-> "#PBS" are Batch Script commands

#PBS -m abe

################ Verbose mode

#PBS -V

################

################ Change these parameters according to your requisites

#PBS -l nodes=4:ppn=16:cluster-Grad,walltime=00:00:30

################ Where:
################ nodes = number of nodes requested
################ ppn = number of cores per node
################ cluster-Atlantica / cluster-Gates = cluster name
################ walltime = max allocation time

################ Please, change this e-mail address to yours

#PBS -M rafaelcompanhonigcp@gmail.com

################

#PBS -r n

################ Output options

#PBS -j oe

################

################ Please, change this directory to your working dir.

#PBS -d /home/pp12712/parallel-computing/demo


################

################
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo ################

############# Command example, if using MPI

# CENÁRIO 1
# mpirun --bynode -np 2 final

# CENÁRIO 2
# mpirun --bynode -np 3 final

# CENÁRIO 3
#mpirun --bynode -np 4 final

# CENÁRIO 4
mpirun --bynode -np 5 final

################

echo Final Time is `date`

